# Generated by Django 3.0.6 on 2020-05-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_facultyapi'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_assesment', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('verified_api_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('nature_of_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.FacultyProfile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='facultyapi',
            constraint=models.UniqueConstraint(fields=('nature_of_activity', 'user'), name='faculty_api'),
        ),
    ]
