# Generated by Django 3.0.6 on 2020-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='self_assesment',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='verified_api_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='api',
            unique_together={('stream', 'nature_of_activity')},
        ),
        migrations.AlterUniqueTogether(
            name='categorystream',
            unique_together={('category_id', 'stream')},
        ),
    ]
