# Generated by Django 3.0.6 on 2020-05-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200529_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystream',
            name='stream',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='api',
            unique_together={('stream', 'nature_of_activity')},
        ),
        migrations.AlterUniqueTogether(
            name='categorystream',
            unique_together={('category_id', 'stream')},
        ),
    ]
