# Generated by Django 3.0.6 on 2020-05-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200529_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CategoryStream'),
        ),
    ]
