# Generated by Django 3.0.6 on 2020-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200529_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='self_assesment',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='verified_api_score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
