# Generated by Django 3.0.6 on 2020-05-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200529_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='api',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='categorystream',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='api',
            constraint=models.UniqueConstraint(fields=('nature_of_activity', 'stream'), name='api'),
        ),
        migrations.AddConstraint(
            model_name='categorystream',
            constraint=models.UniqueConstraint(fields=('category_id', 'stream'), name='category_stream'),
        ),
    ]
