# Generated by Django 3.0.6 on 2020-05-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '__first__'),
        ('user', '0003_auto_20200529_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='nature_of_activity',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='self_assesment',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='verified_api_score',
        ),
        migrations.CreateModel(
            name='FacultyApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_assesment', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('verified_api_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('nature_of_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.FacultyProfile')),
            ],
        ),
    ]
