# Generated by Django 3.0.6 on 2020-05-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200529_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyapi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.FacultyProfile'),
        ),
    ]
