# Generated by Django 3.0.6 on 2020-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200529_2030'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facultyapi',
            constraint=models.UniqueConstraint(fields=('nature_of_activity', 'user'), name='faculty_api'),
        ),
    ]
