# Generated by Django 3.0.6 on 2020-05-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200529_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyApi',
        ),
    ]
