# Generated by Django 3.0.6 on 2020-05-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_facultyapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='stream',
            field=models.CharField(choices=[('', '----'), ('FOLA/H/SS/L/PEM', 'Faculties of Languages Arts/Humanities/Social Sciences/Library/Physical education/Management'), ('E/A/VS/S/MS', 'Engineering/Agriculture/Veterinary Science/Sciences/Medical Sciences')], max_length=60),
        ),
    ]
